# Generated by Django 5.1.15 on 2026-09-02 18:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resumes', '0003_alter_resume_options_alter_resumeanalysis_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=1)),
                ('category', models.CharField(default='TECHNICAL', max_length=50)),
                ('question_text', models.TextField()),
                ('expected_key_points', models.JSONField(blank=True, default=list)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='InterviewResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_answer', models.TextField()),
                ('technical_score', models.IntegerField(default=0)),
                ('clarity_score', models.IntegerField(default=0)),
                ('relevance_score', models.IntegerField(default=0)),
                ('overall_score', models.IntegerField(default=0)),
                ('strengths', models.JSONField(blank=True, default=list)),
                ('improvements', models.JSONField(blank=True, default=list)),
                ('ideal_answer', models.TextField(blank=True, default='')),
                ('ai_feedback', models.TextField(blank=True, default='')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='response', to='interviews.interviewquestion')),
            ],
        ),
        migrations.CreateModel(
            name='InterviewSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_title', models.CharField(max_length=255)),
                ('job_description', models.TextField(blank=True, default='')),
                ('difficulty', models.CharField(choices=[('ENTRY', 'Entry Level'), ('MID', 'Mid Level'), ('SENIOR', 'Senior Level'), ('LEAD', 'Lead / Staff')], default='MID', max_length=20)),
                ('interview_type', models.CharField(choices=[('TECHNICAL', 'Technical'), ('BEHAVIORAL', 'Behavioral'), ('MIXED', 'Mixed (Technical & Behavioral)'), ('SYSTEM_DESIGN', 'System Design')], default='MIXED', max_length=30)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='IN_PROGRESS', max_length=20)),
                ('total_questions', models.IntegerField(default=5)),
                ('overall_score', models.FloatField(blank=True, null=True)),
                ('technical_mastery', models.IntegerField(blank=True, null=True)),
                ('communication_clarity', models.IntegerField(blank=True, null=True)),
                ('problem_solving', models.IntegerField(blank=True, null=True)),
                ('readiness_rating', models.CharField(blank=True, default='', max_length=100)),
                ('key_takeaways', models.JSONField(blank=True, default=list)),
                ('actionable_recommendations', models.JSONField(blank=True, default=list)),
                ('detailed_summary', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('resume', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interview_sessions', to='resumes.resume')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddField(
            model_name='interviewquestion',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='interviews.interviewsession'),
        ),
    ]
