# Generated by Django 5.1.15 on 2026-09-02 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0002_resumeanalysis'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resume',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.AlterModelOptions(
            name='resumeanalysis',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='resumeanalysis',
            name='missing_keywords',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='resumeanalysis',
            name='soft_skills',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='resumeanalysis',
            name='suggested_roles',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='resume',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='resumeanalysis',
            name='ats_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='resumeanalysis',
            name='extracted_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='resumeanalysis',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='resumeanalysis',
            name='skills',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='resumeanalysis',
            name='strengths',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='resumeanalysis',
            name='summary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='resumeanalysis',
            name='weaknesses',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
